### ISSUE TITLE
Problems when I try to compile

### ISSUE THREAD

**Issue by DarcyNing** [vincentbernat/rfc5077#11] opened 2017-03-18 10:06 UTC
When I wanted to compile this soft, a problem occurred, can anyone help?

Hereafter is the problem details

cc -g -Werror -Wall -ansi -std=c99 -D_DEFAULT_SOURCE -D_GNU_SOURCE   -c -o rfc5077-client.o rfc5077-client.c
cc -g -Werror -Wall -ansi -std=c99 -D_DEFAULT_SOURCE -D_GNU_SOURCE   -c -o common.o common.c
cc -o rfc5077-client rfc5077-client.o common.o  -lssl -lcrypto  
rfc5077-client.o: In function `resultinfo_display':
/usr/local/src/rfc5077/rfc5077-client.c:131: undefined reference to `SSL_SESSION_get0_cipher'
/usr/local/src/rfc5077/rfc5077-client.c:153: undefined reference to `SSL_SESSION_get_master_key'
/usr/local/src/rfc5077/rfc5077-client.c:160: undefined reference to `SSL_SESSION_get_master_key'
/usr/local/src/rfc5077/rfc5077-client.c:169: undefined reference to `SSL_SESSION_has_ticket'
rfc5077-client.o: In function `resultinfo_write':
/usr/local/src/rfc5077/rfc5077-client.c:204: undefined reference to `SSL_SESSION_get0_cipher'
/usr/local/src/rfc5077/rfc5077-client.c:216: undefined reference to `SSL_SESSION_get_master_key'
/usr/local/src/rfc5077/rfc5077-client.c:219: undefined reference to `SSL_SESSION_get_master_key'
/usr/local/src/rfc5077/rfc5077-client.c:223: undefined reference to `SSL_SESSION_has_ticket'
rfc5077-client.o: In function `tests':
/usr/local/src/rfc5077/rfc5077-client.c:278: undefined reference to `SSL_set_options'
/usr/local/src/rfc5077/rfc5077-client.c:297: undefined reference to `SSL_session_reused'
rfc5077-client.o: In function `main':
/usr/local/src/rfc5077/rfc5077-client.c:378: undefined reference to `OPENSSL_init_ssl'
/usr/local/src/rfc5077/rfc5077-client.c:379: undefined reference to `OPENSSL_init_ssl'
/usr/local/src/rfc5077/rfc5077-client.c:380: undefined reference to `TLS_client_method'
collect2: ld returned 1 exit status
make: *** [rfc5077-client] Error 1

**Comment by vincentbernat** [comment] 2017-03-18 11:04
Duplicate of #10.

**Closed by vincentbernat** 2017-03-18 11:04 UTC
